name: MegaLinter

on:
  push:
  pull_request:
    branches: [develop, main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run MegaLinter
        uses: oxsecurity/megalinter@v6
        env:
          MEGALINTER_CONFIG: ${{ join(github.workspace, '/.mega-linter/config.yml') }}
